"""1_user

Revision ID: bd2f5b6cf562
Revises: 
Create Date: 2022-11-16 21:13:45.185313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd2f5b6cf562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('private_metadata', sa.JSON(), nullable=False),
                    sa.Column('public_metadata', sa.JSON(), nullable=False),
                    sa.Column('full_name', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=500), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('language_code', sa.String(length=5), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
