"""3_transaction

Revision ID: fbb20702b424
Revises: e41761dd5672
Create Date: 2022-11-16 21:29:39.867834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

from app.contrib.transaction import TransactionStatusChoices, TransactionTypeChoices

# revision identifiers, used by Alembic.
revision = 'fbb20702b424'
down_revision = 'e41761dd5672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('private_metadata', sa.JSON(), nullable=False),
                    sa.Column('public_metadata', sa.JSON(), nullable=False),
                    sa.Column('to_wallet_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('from_wallet_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('transaction_type', sqlalchemy_utils.types.choice.ChoiceType(
                        choices=TransactionTypeChoices, impl=sa.String(length=13)), nullable=False, ),
                    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(
                        choices=TransactionStatusChoices,
                        impl=sa.String(length=10)), nullable=False, default=TransactionStatusChoices.PROCESSING),
                    sa.ForeignKeyConstraint(('from_wallet_id',), ['wallet.id'], name='fx_tr_from_wl_id',
                                            ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(('to_wallet_id',), ['wallet.id'], name='fx_tr_to_wl_id',
                                            ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
